// Standard abbreviations for Bible books
export const BOOK_ABBREVIATIONS = {
  Genesis: 'Gen',
  Exodus: 'Exod',
  Leviticus: 'Lev',
  Numbers: 'Num',
  Deuteronomy: 'Deut',
  Joshua: 'Josh',
  Judges: 'Judg',
  Ruth: 'Ruth',
  '1 Samuel': '1 Sam',
  '2 Samuel': '2 Sam',
  '1 Kings': '1 Kgs',
  '2 Kings': '2 Kgs',
  '1 Chronicles': '1 Chr',
  '2 Chronicles': '2 Chr',
  Ezra: 'Ezra',
  Nehemiah: 'Neh',
  Esther: 'Esth',
  Job: 'Job',
  Psalms: 'Ps',
  Proverbs: 'Prov',
  Ecclesiastes: 'Eccl',
  'Song of Solomon': 'Song',
  Isaiah: 'Isa',
  Jeremiah: 'Jer',
  Lamentations: 'Lam',
  Ezekiel: 'Ezek',
  Daniel: 'Dan',
  Hosea: 'Hos',
  Joel: 'Joel',
  Amos: 'Amos',
  Obadiah: 'Obad',
  Jonah: 'Jonah',
  Micah: 'Mic',
  Nahum: 'Nah',
  Habakkuk: 'Hab',
  Zephaniah: 'Zeph',
  Haggai: 'Hag',
  Zechariah: 'Zech',
  Malachi: 'Mal',
  Tobit: 'Tob',
  Judith: 'Jdt',
  'Esther (Greek)': 'Esth Gr',
  'Wisdom of Solomon': 'Wis',
  Sirach: 'Sir',
  Baruch: 'Bar',
  'Letter of Jeremiah': 'Let Jer',
  'Song of the Three Young Men': 'S3Y',
  Susanna: 'Sus',
  'Bel and the Dragon': 'Bel',
  '1 Maccabees': '1 Mac',
  '2 Maccabees': '2 Mac',
  '3 Maccabees': '3 Mac',
  '4 Maccabees': '4 Mac',
  'Prayer of Manasseh': 'Pr Man',
  'Ezra (Greek)': 'Ezra Gr',
  'Psalm 151': 'Ps 151',
  Odes: 'Odes',
  'Psalms (Extra)': 'PsX',
  Matthew: 'Matt',
  Mark: 'Mark',
  Luke: 'Luke',
  John: 'John',
  Acts: 'Acts',
  Romans: 'Rom',
  '1 Corinthians': '1 Cor',
  '2 Corinthians': '2 Cor',
  Galatians: 'Gal',
  Ephesians: 'Eph',
  Philippians: 'Phil',
  Colossians: 'Col',
  '1 Thessalonians': '1 Thess',
  '2 Thessalonians': '2 Thess',
  '1 Timothy': '1 Tim',
  '2 Timothy': '2 Tim',
  Titus: 'Titus',
  Philemon: 'Phlm',
  Hebrews: 'Heb',
  James: 'Jas',
  '1 Peter': '1 Pet',
  '2 Peter': '2 Pet',
  '1 John': '1 John',
  '2 John': '2 John',
  '3 John': '3 John',
  Jude: 'Jude',
  Revelation: 'Rev'
};
